# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Config host information to expose http server
  config.vm.network :forwarded_port, guest: 4242, host: 4242, guest_ip: "127.0.0.1"

  # Config VirtualBox options
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false

    vb.name = "perf.html"

    vb.memory = "1024"
    vb.cpus = 2
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "bootstap", type: "shell", inline: <<-BOOT
#!/usr/bin/env bash
# Get up to date
apt-get update
apt-get upgrade -y

# Setup NodeSource
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

# Setup yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | \
  sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | \
  sudo tee /etc/apt/sources.list.d/yarn.list

# Install node and yarn
apt-get update
apt-get install -y nodejs yarn

BOOT
end
